# url: https://127.0.0.1
# baseurl: ""

url: https://crest-socio-technical.github.io/
baseurl: ""

# Site settings
title: CREST Socio-Technical
email: asangi.jayathilaka@adelaide.edu.au
description: "Socio-Technical Research Cluster"


# Team names, titles and social links
faculty:
- name: Prof. M. Ali Babar
  pic: ali
  position: Professor & Director CREST
  social:
    - title: link
      url: https://malibabar.wordpress.com/
    - title: twitter
      url: https://twitter.com/alibabar
    - title: linkedin
      url: https://www.linkedin.com/in/ali-babar-5bb4884
      
- name: Sherif Haggag
  pic: sherif
  position: Lecturer(Assistant Professor)
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/sherif-haggag/
      
peoplex:
- name: Asangi Jayatilaka
  pic: asangi
  position: Post Doc
  social:
    - title: twitter
      url: https://twitter.com/DrAsangiJ
    - title: linkedin
      url: https://www.linkedin.com/in/asangi-jayatilaka/

- name: Nesara Dissanayake
  pic: nesara
  position: PhD. Student
  social:
    - title: twitter
      url: https://twitter.com/nesara_d
    - title: linkedin
      url: https://www.linkedin.com/in/nesarad/

- name: Roshan Rajapakse
  pic: roshan
  position: PhD. Student
  social:
    - title: twitter
      url: https://twitter.com/rosh_nr
    - title: linkedin
      url: https://www.linkedin.com/in/roshanrajapakse/

- name: Orvila Sarker
  pic: orvila
  position: PhD. Student
  social:
    - title: twitter
      url: https://twitter.com/OrvilaSarker
    - title: linkedin
      url: https://www.linkedin.com/in/orvila-sarker-03941814b/
      
- name: Isuru Dharmadasa
  pic: isuru
  position: PhD. Student
  social:
    - title: link
      url: https://sites.google.com/view/isuru-dharmadasa/
    - title: twitter
      url: https://twitter.com/isurudharmadasa
    - title: linkedin
      url: https://www.linkedin.com/in/isurudharmadasa/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: link
    url: https://www.crest-centre.net/
  - title: twitter
    url: https://twitter.com/crest_uofa
  - title: linkedin
    url: https://www.linkedin.com/company/72018457/

# Postal address (add as many lines as necessary)
address:
  - line: The University of Adelaide
  - line: Ingkarni Wardli
  - line: Adelaide SA 5005

# Build settings
markdown: kramdown
permalink: pretty
