# url: https://127.0.0.1
# baseurl: ""

url: http://ssi.crest-centre.net
baseurl: ""

# Site settings
title: CREST Socio-Technical
email: roland.croft@adelaide.edu.au
description: "Socio-Technical Research Cluster"


# Team names, titles and social links
people:
- name: Prof. M. Ali Babar
  pic: ali
  position: CREST Director
  social:
    - title: link
      url: https://malibabar.wordpress.com/
    - title: twitter
      url: https://twitter.com/alibabar
    - title: linkedin
      url: https://www.linkedin.com/in/ali-babar-5bb4884

- name: Asangi Jayatilaka
  pic: asangi
  position: Post-Doctorate
  social:
    - title: link
      url: https://sites.google.com/site/triethmle
    - title: twitter
      url: https://twitter.com/lhmtriet
    - title: linkedin
      url: https://www.linkedin.com/in/triet-le-274407133/

- name: Roshan Rajapakse
  pic: roshan
  position: PhD. Student
  social:
    - title: link
      url: https://github.com/RoshanRajapakse
    - title: twitter
      url:https://twitter.com/rosh_nr
    - title: linkedin
      url: https://www.linkedin.com/in/roshanrajapakse/




# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: link
    url: https://www.crest-centre.net/
  - title: twitter
    url: https://twitter.com/crest_uofa
  - title: linkedin
    url: https://www.linkedin.com/company/72018457/

# Postal address (add as many lines as necessary)
address:
  - line: The University of Adelaide
  - line: Ingkarni Wardli
  - line: Adelaide SA 5005

# Build settings
markdown: kramdown
permalink: pretty
